on: push

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - run: npm --version
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
